package net.me.skyblock.item;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.me.skyblock.SkyBlock;
import net.me.skyblock.block.ModBlocks;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class ModItemGroup {
    public static ItemGroup FYBERITE = Registry.register(Registries.ITEM_GROUP, new Identifier(SkyBlock.MOD_ID, "citrine"),
            FabricItemGroup.builder().displayName(Text.literal("Sky Block: Feature (Qbaesz13, SoryYPMod)")).icon(() -> new ItemStack(ModItems.ENDERITE_SWORD)).entries((displayContext, entries) -> {
                entries.add(ModItems.ENDERITE_INGOT);
                entries.add(ModItems.ENDERITE_APPLE);
                entries.add(ModItems.ENCHANTED_ENDERITE_APPLE);
                entries.add(ModItems.ENDER_STICK);
                entries.add(ModItems.ENDMERALD);
                entries.add(ModItems.MELTE_RESIDUES);
                entries.add(ModItems.ENDERITE_HELMET);
                entries.add(ModItems.ENDERITE_CHESTPLATE);
                entries.add(ModItems.ENDERITE_LEGGINGS);
                entries.add(ModItems.ENDERITE_BOOTS);
                entries.add(ModItems.ENDERITE_SWORD);
                entries.add(ModItems.ENDERITE_AXE);
                entries.add(ModItems.ENDERITE_SHOVEL);
                entries.add(ModItems.ENDERITE_HOE);
                entries.add(ModItems.ENDERITE_PICKAXE);
                entries.add(ModItems.BOTTLE_OF_ANT_JAM);
                entries.add(ModBlocks.ENDMERALD_ORE);
                entries.add(ModBlocks.ENDMERALD_BLOCK);
                entries.add(ModBlocks.ENDERITE_ORE);
                entries.add(ModBlocks.ENDERITE_BLOCK);
                entries.add(ModBlocks.ASTEROID_RESIDUES);
                entries.add(ModBlocks.SOLID_ROCK);
                entries.add(ModBlocks.END_GRASS);
                entries.add(ModBlocks.BLUISHE_GRASS);
                entries.add(ModBlocks.ANT_JAM_BLOCK);
                entries.add(ModBlocks.SUSPICIOUS_COARSE_DIRT);
                entries.add(ModBlocks.TRANSPARENT_BLOCK);
                entries.add(ModBlocks.END_WART_BLOCK);
                entries.add(ModBlocks.BLUE_WART);
                entries.add(ModBlocks.END_STEM);
                entries.add(ModBlocks.END_HYPHAE);
                entries.add(ModBlocks.STRIPPED_END_STEM);
                entries.add(ModBlocks.STRIPPED_END_HYPHAE);
                entries.add(ModBlocks.END_PLANKS);
                entries.add(ModBlocks.END_STAIRS);
                entries.add(ModBlocks.END_SLAB);
                entries.add(ModBlocks.ENDLIGHT);
                entries.add(ModBlocks.BLUISHE_STEM);
                entries.add(ModBlocks.BLUISHE_HYPHAE);
                entries.add(ModBlocks.BLUISHE_LIGHT_STEM);
                entries.add(ModBlocks.BLUISHE_LIGHT_HYPHAE);
                entries.add(ModBlocks.STRIPPED_BLUISHE_STEM);
                entries.add(ModBlocks.STRIPPED_BLUISHE_HYPHAE);
                entries.add(ModBlocks.BLUISHE_PLANKS);
                entries.add(ModBlocks.BLUISHE_STAIRS);
                entries.add(ModBlocks.BLUISHE_SLAB);
                entries.add(ModBlocks.AZALEA_LOG);
                entries.add(ModBlocks.AZALEA_WOOD);
                entries.add(ModBlocks.STRIPPED_AZALEA_LOG);
                entries.add(ModBlocks.STRIPPED_AZALEA_WOOD);
                entries.add(ModBlocks.AZALEA_PLANKS);
                entries.add(ModBlocks.AZALEA_STAIRS);
                entries.add(ModBlocks.AZALEA_SLAB);
            }).build());
    public static ItemGroup MCD = Registry.register(Registries.ITEM_GROUP, new Identifier(SkyBlock.MOD_ID,"minecraft_dungeons"),
            FabricItemGroup.builder().displayName(Text.literal("Sky Block: Minecraft Dungeons (ilosemypotato)")).icon(() -> new ItemStack(ModItems.TWIN_BOW)).entries((displayContext, entries) -> {
                entries.add(ModItems.SHORTBOW);
                entries.add(ModItems.LONGBOW);
                entries.add(ModItems.TWIN_BOW);
                entries.add(ModItems.AUTO_CROSSBOW);
                entries.add(ModItems.WOODEN_RAPIER);
                entries.add(ModItems.STONE_RAPIER);
                entries.add(ModItems.IRON_RAPIER);
                entries.add(ModItems.GOLDEN_RAPIER);
                entries.add(ModItems.DIAMOND_RAPIER);
                entries.add(ModItems.NETHERITE_RAPIER);
                entries.add(ModBlocks.MOSSIER_COBBLESTONE);
                entries.add(ModBlocks.MOSSIER_OAK_PLANKS);
                entries.add(ModBlocks.MOSSIER_SPRUCE_PLANKS);
            }).build());
    public static ItemGroup UNUSED = Registry.register(Registries.ITEM_GROUP, new Identifier(SkyBlock.MOD_ID,"unused"),
            FabricItemGroup.builder().displayName(Text.literal("Sky Block: Unused (Qbaesz13)")).icon(() -> new ItemStack(ModItems.FYBERITE)).entries((displayContext, entries) -> {
                entries.add(ModItems.MUSIC_DISC_WITHERSTORM);
                entries.add(ModItems.DISC_FRAGMENT_WITHERSTORM);
                entries.add(ModItems.FYBERITE);
                entries.add(ModItems.SUGAR_POPPY_MIXTURE);
                entries.add(ModItems.STEAM_DUMPLING_FRESH);
                entries.add(ModItems.STEAM_DUMPLING);
                entries.add(ModItems.STEAM_DUMPLING_WITH_MOLTEN_BUTTER);
                entries.add(ModItems.STEAM_DUMPLING_WITH_MOLTEN_BUTTER_AND_SUGAR_POPPY_MIXTURE);
                entries.add(ModBlocks.VOID_BLOCK);
                entries.add(ModBlocks.ABYSS_STONE_OG);
                entries.add(ModBlocks.STRIPPED_ABYSCULK_LOG);
                entries.add(ModBlocks.STRIPPED_ABYSCULK_WOOD);
                entries.add(ModBlocks.SWEET_BERRY_JAM_BLOCK);
                entries.add(ModItems.LIGHTNING_SWORD);
            }).build());
    public static ItemGroup ABYSS = Registry.register(Registries.ITEM_GROUP, new Identifier(SkyBlock.MOD_ID,"classified"),
            FabricItemGroup.builder().displayName(Text.literal("The Abyss Chapter II: Feature (Y3Z0N)")).icon(() -> new ItemStack(ModItems.LORAN)).entries((displayContext, entries) -> {
                entries.add(ModItems.ABERYTHE_GEM);
                entries.add(ModItems.ABERYTHE_HELMET);
                entries.add(ModItems.ABERYTHE_CHESTPLATE);
                entries.add(ModItems.ABERYTHE_LEGGINGS);
                entries.add(ModItems.ABERYTHE_BOOTS);
                entries.add(ModItems.ABERYTHE_SWORD);
                entries.add(ModItems.ABERYTHE_AXE);
                entries.add(ModItems.ABERYTHE_SHOVEL);
                entries.add(ModItems.ABERYTHE_HOE);
                entries.add(ModItems.ABERYTHE_PICKAXE);
                entries.add(ModItems.LORAN);
                entries.add(ModItems.ABYSS_PORTAL_ACTIVATOR);
                entries.add(ModBlocks.UNSTABLE_OBSIDIAN);
                entries.add(ModBlocks.ABYSS_DIRT);
                entries.add(ModBlocks.ROMA_MUD);
                entries.add(ModBlocks.ROMA_MUD_CURSED);
                entries.add(ModBlocks.ABYSS_GRAVEL);
                entries.add(ModBlocks.INFECTED_PEAT);
                entries.add(ModBlocks.STONE_RACKLE);
                entries.add(ModBlocks.BLARU_MOSS);
                entries.add(ModBlocks.GLOWING_BLARU_MOSS);
                entries.add(ModBlocks.BLARU_GRASS);
                entries.add(ModBlocks.ABYSS_SPORES);
                entries.add(ModBlocks.TESLA_FLOWER);
                entries.add(ModBlocks.VIGILANT_VERSA);
                entries.add(ModBlocks.EXOLIUS_MAXIMUS);
                entries.add(ModBlocks.YOUNG_EXOLIUS_MAXIMUS);
                entries.add(ModBlocks.VIGILANT_GRASS);
                entries.add(ModBlocks.BLUE_VIGILANT_GRASS);
                entries.add(ModBlocks.VIGILANT_MOSS);
                entries.add(ModBlocks.INFUSED_MAGMA);
                entries.add(ModBlocks.ABYSS_STONE);
                entries.add(ModBlocks.ABYSS_DIAMOND_ORE);
                entries.add(ModBlocks.ABYSS_EMERALD_ORE);
                entries.add(ModBlocks.ABYSS_GOLD_ORE);
                entries.add(ModBlocks.ABYSS_IRON_ORE);
                entries.add(ModBlocks.ABYSS_IGNISITHE_ORE);
                entries.add(ModBlocks.ABYSS_ABERYTHE_ORE);
                entries.add(ModBlocks.ABYSS_ABORANYS_ORE);
                entries.add(ModBlocks.ABYSS_FUSION_ORE);
                entries.add(ModBlocks.ABYSS_GARNITE_ORE);
                entries.add(ModBlocks.ABYSS_GLACERYTHE_ORE);
                entries.add(ModBlocks.ABYSS_INCORYTHE_ORE);
                entries.add(ModBlocks.ABYSS_LORAN_ORE);
                entries.add(ModBlocks.PURPLE_SHROOMLIGHT);
                entries.add(ModBlocks.DARK_BLUE_SHROOMLIGHT);
                entries.add(ModBlocks.BLUE_SHROOMLIGHT);
                entries.add(ModBlocks.ABYSS_JUNGLE_LOG);
                entries.add(ModBlocks.ABYSS_JUNGLE_WOOD);
                entries.add(ModBlocks.STRIPPED_ABYSS_JUNGLE_LOG);
                entries.add(ModBlocks.STRIPPED_ABYSS_JUNGLE_WOOD);
                entries.add(ModBlocks.ABYSS_JUNGLE_PLANKS);
                entries.add(ModBlocks.ABYSS_JUNGLE_STAIRS);
                entries.add(ModBlocks.ABYSS_JUNGLE_SLAB);
                entries.add(ModBlocks.ABYSS_JUNGLE_LEAVES);
                entries.add(ModBlocks.BLARU_LOG);
                entries.add(ModBlocks.BLARU_WOOD);
                entries.add(ModBlocks.STRIPPED_BLARU_LOG);
                entries.add(ModBlocks.STRIPPED_BLARU_WOOD);
                entries.add(ModBlocks.BLARU_PLANKS);
                entries.add(ModBlocks.BLARU_STAIRS);
                entries.add(ModBlocks.BLARU_SLAB);
                entries.add(ModBlocks.BLARU_LEAVES);
                entries.add(ModBlocks.FROZEN_LOG);
                entries.add(ModBlocks.FROZEN_WOOD);
                entries.add(ModBlocks.STRIPPED_FROZEN_LOG);
                entries.add(ModBlocks.STRIPPED_FROZEN_WOOD);
                entries.add(ModBlocks.FROZEN_PLANKS);
                entries.add(ModBlocks.FROZEN_STAIRS);
                entries.add(ModBlocks.FROZEN_SLAB);
                entries.add(ModBlocks.FROZEN_LEAVES);
                entries.add(ModBlocks.SLIMED_LOG);
                entries.add(ModBlocks.SLIMED_WOOD);
                entries.add(ModBlocks.STRIPPED_SLIMED_LOG);
                entries.add(ModBlocks.STRIPPED_SLIMED_WOOD);
                entries.add(ModBlocks.SLIMED_PLANKS);
                entries.add(ModBlocks.SLIMED_STAIRS);
                entries.add(ModBlocks.SLIMED_SLAB);
                entries.add(ModBlocks.ABYSS_SLIME_BLOCK);
                entries.add(ModBlocks.VIGILANT_LOG);
                entries.add(ModBlocks.VIGILANT_WOOD);
                entries.add(ModBlocks.STRIPPED_VIGILANT_LOG);
                entries.add(ModBlocks.STRIPPED_VIGILANT_WOOD);
                entries.add(ModBlocks.VIGILANT_PLANKS);
                entries.add(ModBlocks.VIGILANT_STAIRS);
                entries.add(ModBlocks.VIGILANT_SLAB);
                entries.add(ModBlocks.VIGILANT_LEAVES);
                entries.add(ModBlocks.BOG_SHROOM_LOG);
                entries.add(ModBlocks.BOG_SHROOM_WOOD);
                entries.add(ModBlocks.STRIPPED_BOG_SHROOM_LOG);
                entries.add(ModBlocks.STRIPPED_BOG_SHROOM_WOOD);
                entries.add(ModBlocks.BOG_SHROOM_PLANKS);
                entries.add(ModBlocks.BOG_SHROOM_STAIRS);
                entries.add(ModBlocks.BOG_SHROOM_SLAB);
                entries.add(ModBlocks.BOG_SHROOM_LEAVES);
                entries.add(ModBlocks.SAL_SHROOM_LOG);
                entries.add(ModBlocks.SAL_SHROOM_WOOD);
                entries.add(ModBlocks.STRIPPED_SAL_SHROOM_LOG);
                entries.add(ModBlocks.STRIPPED_SAL_SHROOM_WOOD);
                entries.add(ModBlocks.SAL_SHROOM_PLANKS);
                entries.add(ModBlocks.SAL_SHROOM_STAIRS);
                entries.add(ModBlocks.SAL_SHROOM_SLAB);
                entries.add(ModBlocks.SAL_SHROOM_LEAVES);
                entries.add(ModBlocks.ABYSCULK_LOG);
                entries.add(ModBlocks.ABYSCULK_WOOD);
                entries.add(ModBlocks.ABYSCULK_PLANKS);
                entries.add(ModBlocks.ABYSCULK_STAIRS);
                entries.add(ModBlocks.ABYSCULK_SLAB);
            }).build());
    public static ItemGroup QUARK = Registry.register(Registries.ITEM_GROUP, new Identifier(SkyBlock.MOD_ID,"quark"),
            FabricItemGroup.builder().displayName(Text.literal("Quark: Features (Vazkii)")).icon(() -> new ItemStack(ModBlocks.APPLE_CRATE)).entries((displayContext, entries) -> {
                entries.add(ModBlocks.APPLE_CRATE);
                entries.add(ModBlocks.BEETROOT_CRATE);
                entries.add(ModBlocks.CARROT_CRATE);
                entries.add(ModBlocks.POTATO_CRATE);
                entries.add(ModBlocks.GOLDEN_APPLE_CRATE);
                entries.add(ModBlocks.GOLDEN_CARROT_CRATE);
                entries.add(ModBlocks.SWEET_BERRY_SACK);
                entries.add(ModBlocks.GLOW_BERRY_SACK);
                entries.add(ModBlocks.COCOA_BEANS_SACK);
                entries.add(ModBlocks.GUNPOWDER_SACK);
                entries.add(ModBlocks.NETHER_WART_SACK);
                entries.add(ModBlocks.STICK_BLOCK);
                entries.add(ModBlocks.SUGAR_CANE_BLOCK);
                entries.add(ModBlocks.CACTUS_BLOCK);
                entries.add(ModBlocks.CHORUS_FRUIT_BLOCK);
                entries.add(ModBlocks.ANDESITE_PILLAR);
                entries.add(ModBlocks.DIORITE_PILLAR);
                entries.add(ModBlocks.GRANITE_PILLAR);
                entries.add(ModBlocks.CAVE_ROOTS);
            }).build());
    public static ItemGroup PEARFECTION = Registry.register(Registries.ITEM_GROUP, new Identifier(SkyBlock.MOD_ID,"pearfection"),
            FabricItemGroup.builder().displayName(Text.literal("Pearfection: Feature (DigitalPear_11)")).icon(() -> new ItemStack(ModBlocks.FLOWERING_CALLERY_LEAVES)).entries((displayContext, entries) -> {
                entries.add(ModBlocks.CALLERY_LOG);
                entries.add(ModBlocks.CALLERY_WOOD);
                entries.add(ModBlocks.STRIPPED_CALLERY_LOG);
                entries.add(ModBlocks.STRIPPED_CALLERY_WOOD);
                entries.add(ModBlocks.CALLERY_PLANKS);
                entries.add(ModBlocks.CALLERY_STAIRS);
                entries.add(ModBlocks.CALLERY_SLAB);
                entries.add(ModBlocks.CALLERY_LEAVES);
                entries.add(ModBlocks.FLOWERING_CALLERY_LEAVES);
            }).build());

    public static void registerItemGroups() {}
}
