package net.me.skyblock.blocks_and_items;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.me.skyblock.SkyBlock;
import net.me.skyblock.archived.ArchivedBlocks;
import net.me.skyblock.archived.ArchivedItems;
import net.me.skyblock.blocks_and_items.items.util.GhostItems;
import net.me.skyblock.blocks_and_items.items.util.NullItem;
import net.me.skyblock.component.ModDataComponentTypes;
import net.me.skyblock.component.util.SimpleByteValueComponent;
import net.minecraft.block.Blocks;
import net.minecraft.item.ItemConvertible;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.text.Text;

public class ModItemGroups {
    public static final ItemGroup SKYBLOCK_FEATURES = SkyBlock.BuiltinRegistries.registerItemGroup( "skyblock_features",
            FabricItemGroup.builder().displayName(Text.literal("SkyBlock-Multimod")).icon(() -> new ItemStack(GhostItems.Z__LOGO1)).entries((displayContext, entries) -> {
                entries.add(GhostItems.Z__TILE_SKYBLOCK_1, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK_2, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK_3, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK_4, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK_5, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK_6, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK_7, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK_8, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK_9, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(ModBlocks.SKYBLOCK__FROSTSLATE);
                entries.add(ModBlocks.SKYBLOCK__FROSTSLATE_PILLAR);
                entries.add(ModBlocks.SKYBLOCK__FROSTSLATE_BRICKS);
                entries.add(ModBlocks.SKYBLOCK__FROSTSLATE_BRICK_STAIRS);
                entries.add(ModBlocks.SKYBLOCK__FROSTSLATE_BRICK_SLAB);
                entries.add(ModBlocks.SKYBLOCK__SNOWY_SHORT_GRASS);
                ModItemGroups.addSpaces(entries, 0, 3);
                entries.add(ModItems.SKYBLOCK__BOTTLE_OF_ANT_JAM);
                entries.add(ModBlocks.SKYBLOCK__ANT_JAM_BLOCK);
                entries.add(ModItems.SKYBLOCK__ANT_BOTTLE);
                entries.add(ModBlocks.SKYBLOCK__SUSPICIOUS_COARSE_DIRT);
                ModItemGroups.addSpaces(entries, 3, 5);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2_1, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2_2, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2_3, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2_4, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2_5, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2_6, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2_7, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2_8, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2_9, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(ModBlocks.SKYBLOCK__BOGGED_LOG);
                entries.add(ModBlocks.SKYBLOCK__BOGGED_WOOD);
                entries.add(ModBlocks.SKYBLOCK__BOGGED_PLANKS);
                entries.add(ModBlocks.SKYBLOCK__BOGGED_STAIRS);
                entries.add(ModBlocks.SKYBLOCK__BOGGED_SLAB);
                entries.add(ModItems.SKYBLOCK__DUCKWEED);
                entries.add(ModBlocks.SKYBLOCK__CLOVER);
                entries.add(ModItems.SKYBLOCK__SMALL_LILY_PADS);
                entries.add(ModBlocks.SKYBLOCK__ANCIENT_PEDESTAL);
                entries.add(ModBlocks.SKYBLOCK__WHITE_MUSHROOM_STEM);
                entries.add(ModBlocks.SKYBLOCK__WHITE_MUSHROOM_HYPHAE);
                entries.add(ModBlocks.SKYBLOCK__STRIPPED_MUSHROOM_STEM);
                entries.add(ModBlocks.SKYBLOCK__STRIPPED_MUSHROOM_HYPHAE);
                entries.add(ModBlocks.SKYBLOCK__MUSHROOM_PLANKS);
                entries.add(ModBlocks.SKYBLOCK__VERTICAL_MUSHROOM_PLANKS);
                entries.add(ModBlocks.SKYBLOCK__CARVED_MUSHROOM_PLANKS);
                entries.add(ModBlocks.SKYBLOCK__MUSHROOM_STAIRS);
                entries.add(ModBlocks.SKYBLOCK__MUSHROOM_SLAB);
                entries.add(ModBlocks.SKYBLOCK__FIR_LOG);
                entries.add(ModBlocks.SKYBLOCK__FIR_WOOD);
                entries.add(ModBlocks.SKYBLOCK__STRIPPED_FIR_LOG);
                entries.add(ModBlocks.SKYBLOCK__STRIPPED_FIR_WOOD);
                entries.add(ModBlocks.SKYBLOCK__FIR_PLANKS);
                entries.add(ModBlocks.SKYBLOCK__VERTICAL_FIR_PLANKS);
                entries.add(ModBlocks.SKYBLOCK__CARVED_FIR_PLANKS);
                entries.add(ModBlocks.SKYBLOCK__FIR_STAIRS);
                entries.add(ModBlocks.SKYBLOCK__FIR_SLAB);
                entries.add(ModItems.SKYBLOCK__FIRWOOD_MACE);
                entries.add(ModBlocks.SKYBLOCK__FIR_LEAVES);
                entries.add(ModBlocks.SKYBLOCK__AUTUMN_FIR_LEAVES);
                entries.add(ModBlocks.SKYBLOCK__AUTUMN_BIRCH_LEAVES);
                entries.add(ModBlocks.SKYBLOCK__BLUEBERRY_BUSH);
                entries.add(ModItems.SKYBLOCK__CHILLI_PEPPER_SEEDS);
                ModItemGroups.addSpaces(entries, 8, 3);
                entries.add(ModBlocks.SKYBLOCK__CHILLI_PEPPER_CRATE);
                entries.add(ModItems.SKYBLOCK__CHILLI_PEPPER);
                entries.add(ModBlocks.SKYBLOCK__GOLDEN_CHILLI_PEPPER_CRATE);
                entries.add(ModItems.SKYBLOCK__GOLDEN_CHILLI_PEPPER);
                entries.add(ModBlocks.SKYBLOCK__BLUEBERRY_SACK);
                entries.add(ModItems.SKYBLOCK__BLUEBERRIES);
                entries.add(ModBlocks.SKYBLOCK__BLOCK_OF_EXPERIENCE);
                entries.add(ModItems.CREATE__NUGGET_OF_EXPERIENCE);
                ModItemGroups.addSpaces(entries, 11,1);
                entries.add(Items.OMINOUS_BOTTLE);
                entries.add(ModItems.SKYBLOCK__OMINOUS_LINK);
                entries.add(Items.TOTEM_OF_UNDYING);
                entries.add(ModItems.SKYBLOCK__BONDED_TOTEM_OF_UNDYING);
                entries.add(Items.HEAVY_CORE);
                entries.add(ModItems.SKYBLOCK__COMPRESSED_STEEL);
                entries.add(ModItems.SKYBLOCK__COMMON_TOKEN);
                entries.add(ModItems.SKYBLOCK__UNCOMMON_TOKEN);
                entries.add(ModItems.SKYBLOCK__RARE_TOKEN);
                entries.add(ModBlocks.SKYBLOCK__CARVED_OAK_PLANKS);
                entries.add(ModBlocks.SKYBLOCK__CARVED_SPRUCE_PLANKS);
                entries.add(ModBlocks.SKYBLOCK__CARVED_DARK_OAK_PLANKS);
                entries.add(ModBlocks.ABYSS__CARVED_FROZEN_PLANKS);
                ModItemGroups.addSpaces(entries, 12, 5);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p1_1, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p1_2, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p1_3, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p1_4, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p1_5, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p1_6, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p1_7, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p1_8, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p1_9, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(ModBlocks.BP__PALE_LOG);
                entries.add(ModBlocks.BP__PALE_WOOD);
                entries.add(ModBlocks.BP__STRIPPED_PALE_LOG);
                entries.add(ModBlocks.BP__STRIPPED_PALE_WOOD);
                entries.add(ModBlocks.BP__PALE_PLANKS);
                entries.add(ModBlocks.QUARK__VERTICAL_PALE_OAK_PLANKS);
                entries.add(ModBlocks.SKYBLOCK__CARVED_PALE_OAK_PLANKS);
                entries.add(ModBlocks.BP__PALE_STAIRS);
                entries.add(ModBlocks.BP__PALE_SLAB);
                entries.add(ModBlocks.BP__PALE_LEAVES);
                entries.add(ModBlocks.BP__PALE_MOSS_BLOCK);
                entries.add(ModBlocks.BP__PALE_MOSS_CARPET);
                ModItemGroups.addSpaces(entries, 17, 6);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p2_1, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p2_2, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p2_3, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p2_4, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p2_5, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p2_6, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p2_7, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p2_8, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK2p2_9, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(ModItems.SKYBLOCK__PESTILENT_TROPHY);
                ModItemGroups.addSpaces(entries, 23, 8);
                entries.add(GhostItems.Z__TILE_SKYBLOCK3_1, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK3_2, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK3_3, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK3_4, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK3_5, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK3_6, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK3_7, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK3_8, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SKYBLOCK3_9, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(ModItems.H__ANOMALITE_SWORD);
                entries.add(ModItems.H__ANOMALITE_AXE);
                entries.add(ModItems.H__ANOMALITE_PICKAXE);
                entries.add(ModItems.H__ANOMALITE_FRAGMENT);
                entries.add(ModItems.H__ANOMALITE_HANDLE);
                entries.add(ModItems.H__PEARL_OF_DARKNESS);
                entries.add(ModItems.H__ANOMALITE_HELMET);
                entries.add(ModItems.H__ANOMALITE_CHESTPLATE);
                entries.add(ModItems.H__ANOMALITE_LEGGINGS);
                entries.add(ModItems.H__ANOMALITE_BOOTS);
                entries.add(ModItems.H__NODE_CORE);
                entries.add(ModItems.H__PLASMA_1);
                entries.add(ModItems.H__PLASMA_2);
                entries.add(ModBlocks.H__NODE);
                ModItemGroups.addSpaces(entries, 31, 4);
                entries.add(GhostItems.Z__TILE_SP5_1, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SP5_2, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SP5_3, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SP5_4, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SP5_5, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SP5_6, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SP5_7, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                entries.add(GhostItems.Z__TILE_SP5_8, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
                ModItemGroups.addTiles(entries, 0, 1);
                entries.add(ModItems.SP5__ENDERITE_INGOT);
                entries.add(ModItems.SP5__ENDERITE_APPLE);
                entries.add(ModItems.SP5__ENCHANTED_ENDERITE_APPLE);
                entries.add(ModItems.SP5__ENDER_STICK);
                entries.add(ModItems.SP5__ENDMERALD);
                entries.add(ModItems.SP5__MELTED_RESIDUES);

                entries.add(ModItems.SP5__ENDERITE_HELMET);
                entries.add(ModItems.SP5__ENDERITE_CHESTPLATE);
                entries.add(ModItems.SP5__ENDERITE_LEGGINGS);
                entries.add(ModItems.SP5__ENDERITE_BOOTS);
                entries.add(ModItems.SP5__ENDERITE_SWORD);
                entries.add(ModItems.SP5__ENDERITE_RAPIER);
                entries.add(ModItems.SP5__ENDERITE_AXE);
                entries.add(ModItems.SP5__ENDERITE_SHOVEL);
                entries.add(ModItems.SP5__ENDERITE_HOE);
                entries.add(ModItems.SP5__ENDERITE_PICKAXE);

                entries.add(ModBlocks.SP5__ENDMERALD_ORE);
                entries.add(ModBlocks.SP5__ENDMERALD_BLOCK);

                entries.add(ModBlocks.SP5__ENDERITE_ORE);
                entries.add(ModBlocks.SP5__ENDERITE_BLOCK);

                entries.add(ModBlocks.SP5__ASTEROID_RESIDUES);
                entries.add(ModBlocks.SP5__SOLID_ROCK);

                entries.add(ModBlocks.SP5__END_GRASS);
                entries.add(ModBlocks.SP5__BLUISHE_GRASS);

                entries.add(ModBlocks.SP5__TRANSPARENT_BLOCK);
                entries.add(ModBlocks.SP5__END_WART_BLOCK);
                entries.add(ModBlocks.SP5__BLUE_WART);

                entries.add(ModBlocks.SP5__END_STEM);
                entries.add(ModBlocks.SP5__END_HYPHAE);
                entries.add(ModBlocks.SP5__STRIPPED_END_STEM);
                entries.add(ModBlocks.SP5__STRIPPED_END_HYPHAE);
                entries.add(ModBlocks.SP5__END_PLANKS);
                entries.add(ModBlocks.SP5__END_STAIRS);
                entries.add(ModBlocks.SP5__END_SLAB);
                entries.add(ModBlocks.SP5__ENDLIGHT);

                entries.add(ModBlocks.SP5__BLUISHE_STEM);
                entries.add(ModBlocks.SP5__BLUISHE_HYPHAE);
                entries.add(ModBlocks.SP5__BLUISHE_LIGHT_STEM);
                entries.add(ModBlocks.SP5__BLUISHE_LIGHT_HYPHAE);
                entries.add(ModBlocks.SP5__STRIPPED_BLUISHE_STEM);
                entries.add(ModBlocks.SP5__STRIPPED_BLUISHE_HYPHAE);
                entries.add(ModBlocks.SP5__BLUISHE_PLANKS);
                entries.add(ModBlocks.SP5__BLUISHE_STAIRS);
                entries.add(ModBlocks.SP5__BLUISHE_SLAB);

                entries.add(ModBlocks.SP5__END_GRASS_VEGETATION);
                entries.add(ModBlocks.SP5__END_MUSHROOM);
                entries.add(ModBlocks.SP5__BLUISHE_BUSH);
                entries.add(ModBlocks.SP5__BLUISHE_MUSHROOM);
                entries.add(ModBlocks.SP5__END_BUSH);
                entries.add(ModBlocks.SP5__END_FLOWER);

                entries.add(ModBlocks.SP5__CRACKED_END_STONE_BRICKS);
                entries.add(ModBlocks.SP5__WARPED_END_STONE_BRICKS);
                entries.add(ModBlocks.SP5__END_STONE_PILLAR);
                entries.add(ModBlocks.SP5__END_STONE_TILES);
                entries.add(ModBlocks.SP5__SMALL_END_STONE_BRICKS);
                entries.add(ModBlocks.SP5__SMOOTH_END_STONE);
                entries.add(ModBlocks.SP5__CHISELED_END_STONE);
                entries.add(ModBlocks.SP5__CHISELED_END_STONE_CUBIC);
                entries.add(ModBlocks.SP5__CHISELED_END_STONE_MAZE);

                entries.add(ModBlocks.SP5__PURPLE_END_BRICKS);
                entries.add(ModBlocks.SP5__PURPLE_END_BRICK_PILLAR);
                entries.add(ModBlocks.SP5__WARPED_PURPLE_END_BRICKS);
                entries.add(ModBlocks.SP5__PURPLE_END_BRICK_STAIRS);
                entries.add(ModBlocks.SP5__PURPLE_END_BRICK_SLAB);

                entries.add(ModBlocks.SP5__END_PURPLE_BLOCK);
                entries.add(ModBlocks.SP5__END_PURPLE_PILLAR);
                entries.add(ModBlocks.SP5__ENDER_BLOCK);
                entries.add(ModBlocks.SP5__END_PURPLE_STAIRS);
                entries.add(ModBlocks.SP5__END_PURPLE_SLAB);

                entries.add(ModItems.SP5__ENDERITE_CHORUS_FRUIT);
                entries.add(ModItems.SP5__POPPED_ENDERITE_CHORUS_FRUIT);

                entries.add(ModItems.SP5__BLUISHE_LIGHT_SHEEL);

                entries.add(ModItems.SP5__END_WOODEN_SWORD);
                entries.add(ModItems.SP5__END_WOODEN_RAPIER);
                entries.add(ModItems.SP5__END_WOODEN_AXE);
                entries.add(ModItems.SP5__END_WOODEN_SHOVEL);
                entries.add(ModItems.SP5__END_WOODEN_HOE);
                entries.add(ModItems.SP5__END_WOODEN_PICKAXE);

                entries.add(ModItems.SP5__END_STONE_SWORD);
                entries.add(ModItems.SP5__END_STONE_RAPIER);
                entries.add(ModItems.SP5__END_STONE_AXE);
                entries.add(ModItems.SP5__END_STONE_SHOVEL);
                entries.add(ModItems.SP5__END_STONE_HOE);
                entries.add(ModItems.SP5__END_STONE_PICKAXE);

                entries.add(ModItems.SP5__BLUISHE_SWORD);
                entries.add(ModItems.SP5__BLUISHE_RAPIER);
                entries.add(ModItems.SP5__BLUISHE_AXE);
                entries.add(ModItems.SP5__BLUISHE_SHOVEL);
                entries.add(ModItems.SP5__BLUISHE_HOE);
                entries.add(ModItems.SP5__BLUISHE_PICKAXE);
                ModItemGroups.addSpaces(entries, 35, 0);
                ModItemGroups.addTiles(entries, 1, 9);
                entries.add(Blocks.SCULK);
                entries.add(ModBlocks.BOSC__SCULK_JAW);
                entries.add(ModBlocks.SKYBLOCK__SCULK_SPROUTS);
                entries.add(ModBlocks.SKYBLOCK__RED_SCULK);
                entries.add(ModBlocks.SKYBLOCK__RED_SCULK_JAW);
                entries.add(ModBlocks.SKYBLOCK__RED_SCULK_SPROUTS);
                entries.add(ModBlocks.BOSC__DEAD_SCULK);
                entries.add(ModBlocks.BOSC__DEAD_SCULK_JAW);
                entries.add(ModBlocks.BOSC__DEAD_SCULK_SPROUTS);
                ModItemGroups.addSpaces(entries, 35, 0);
                ModItemGroups.addTiles(entries, 10, 9);
                entries.add(ModBlocks.SKYBLOCK__UNKNOWN_DIRT_NYLIUM);
                entries.add(ModBlocks.SKYBLOCK__UNKNOWN_DIRT);
                entries.add(ModBlocks.SKYBLOCK__UNKNOWN_VEGETATION);
                entries.add(ModBlocks.SKYBLOCK__UNKNOWN_SPROUTS);
                ModItemGroups.addSpaces(entries, 35, 5);
                ModItemGroups.addTiles(entries, 19, 9);
                entries.add(ModBlocks.FLOGICAL__AZALEA_LOG);
                entries.add(ModBlocks.FLOGICAL__AZALEA_WOOD);
                entries.add(ModBlocks.FLOGICAL__STRIPPED_AZALEA_LOG);
                entries.add(ModBlocks.FLOGICAL__STRIPPED_AZALEA_WOOD);
                entries.add(ModBlocks.FLOGICAL__AZALEA_PLANKS);
                entries.add(ModBlocks.FLOGICAL__AZALEA_STAIRS);
                entries.add(ModBlocks.FLOGICAL__AZALEA_SLAB);
                ModItemGroups.addSpaces(entries, 40, 2);
                ModItemGroups.addTiles(entries, 28, 9);
                entries.add(ModBlocks.DIGPEAR__CALLERY_LOG);
                entries.add(ModBlocks.DIGPEAR__CALLERY_WOOD);
                entries.add(ModBlocks.DIGPEAR__STRIPPED_CALLERY_LOG);
                entries.add(ModBlocks.DIGPEAR__STRIPPED_CALLERY_WOOD);
                entries.add(ModBlocks.DIGPEAR__CALLERY_PLANKS);
                entries.add(ModBlocks.DIGPEAR__CALLERY_STAIRS);
                entries.add(ModBlocks.DIGPEAR__CALLERY_SLAB);
                entries.add(ModBlocks.DIGPEAR__CALLERY_LEAVES);
                entries.add(ModBlocks.DIGPEAR__FLOWERING_CALLERY_LEAVES);
                ModItemGroups.addTiles(entries, 37, 9);
            }).build());
    public static ItemGroup MCD = SkyBlock.BuiltinRegistries.registerItemGroup("minecraft_dungeons",
            FabricItemGroup.builder().displayName(Text.literal("SkyBlock: Minecraft Dungeons (ilosemypotato)")).icon(() -> new ItemStack(GhostItems.Z__LOGO2)).entries((displayContext, entries) -> {
                entries.add(ModItems.MCD__SHORTBOW);
                //entries.add(ModItems.MCD__LONGBOW);
                entries.add(ModItems.MCD__TWIN_BOW);
                entries.add(ModItems.MCD__AUTO_CROSSBOW);
                entries.add(ModItems.MCD__WOODEN_RAPIER);
                entries.add(ModItems.MCD__STONE_RAPIER);
                entries.add(ModItems.MCD__IRON_RAPIER);
                entries.add(ModItems.MCD__GOLDEN_RAPIER);
                entries.add(ModItems.MCD__DIAMOND_RAPIER);
                entries.add(ModItems.MCD__NETHERITE_RAPIER);
                entries.add(ModBlocks.MCD__MOSSIER_COBBLESTONE);
                entries.add(ModBlocks.MCD__MIDNIGHT_MOSS_BLOCK);
                entries.add(ModBlocks.MCD__MIDNIGHT_MOSS_CARPET);
                entries.add(ModBlocks.MCD__MIDNIGHT_SPROUTS);
                entries.add(ModBlocks.MCD__POP_FLOWER);
                entries.add(ModBlocks.MCD__MOSSIER_OAK_PLANKS);
                entries.add(ModBlocks.MCD__MOSSIER_SPRUCE_PLANKS);
                entries.add(ModBlocks.MCD__BARREN_GRASS_BLOCK);
                entries.add(ModBlocks.MCD__OG_PURPUR_BLOCK);
                entries.add(ModItems.MCD__ARTIFACT_IRON_HIDE_AMULET);
            }).build());
    public static ItemGroup UNUSED = SkyBlock.BuiltinRegistries.registerItemGroup("unused",
            FabricItemGroup.builder().displayName(Text.literal("SkyBlock: Unused (Qbaesz13)")).icon(() -> new ItemStack(GhostItems.Z__LOGO5)).entries((displayContext, entries) -> {
                invisibleAdd(entries, ModItems.SKYBLOCK__PUFFBALL_FLESH);
                invisibleAdd(entries, ModBlocks.SKYBLOCK__PUFFBALL_MUSHROOM);
                invisibleAdd(entries, ModBlocks.SKYBLOCK__PUFFBALL_MUSHROOM_BLOCK);
                invisibleAdd(entries, ModBlocks.SKYBLOCK__SPORE_PLANTER_BOX);
                invisibleAdd(entries, ModBlocks.SKYBLOCK__PUFFBALL_SPORE_PLANTER_BOX);
                invisibleAdd(entries, ModBlocks.SKYBLOCK__RED_MUSHROOM_SPORE_PLANTER_BOX);
                invisibleAdd(entries, ModItems.WITHERSTORM__MUSIC_DISC_WITHERSTORM);
                invisibleAdd(entries, ModItems.WITHERSTORM__DISC_FRAGMENT_WITHERSTORM);
                invisibleAdd(entries, ModItems.SKYBLOCK__FYBERITE);
                invisibleAdd(entries, ModItems.SKYBLOCK__SUGAR_POPPY_MIXTURE);
                invisibleAdd(entries, ModItems.SKYBLOCK__STEAM_DUMPLING_FRESH);
                invisibleAdd(entries, ModItems.SKYBLOCK__STEAM_DUMPLING);
                invisibleAdd(entries, ModItems.SKYBLOCK__STEAM_DUMPLING_WITH_MOLTEN_BUTTER);
                invisibleAdd(entries, ModItems.SKYBLOCK__STEAM_DUMPLING_WITH_MOLTEN_BUTTER_AND_SUGAR_POPPY_MIXTURE);
                invisibleAdd(entries, ModBlocks.MCD__VOID_BLOCK);
                invisibleAdd(entries, ModBlocks.MCD__STRONGHOLD_DECOR);
                invisibleAdd(entries, ModBlocks.ABYSS__ABYSS_STONE_OG);
                //invisibleAdd(entries, ModBlocks.STRIPPED_ABYSCULK_LOG);
                //invisibleAdd(entries, ModBlocks.STRIPPED_ABYSCULK_WOOD);
                invisibleAdd(entries, ModBlocks.SKYBLOCK__SWEET_BERRY_JAM_BLOCK);
                invisibleAdd(entries, ModItems.SKYBLOCK__LIGHTNING_SWORD);
                invisibleAdd(entries, ModItems.MCD__VILLAGER_STATUE);
                invisibleAdd(entries, ModItems.SP5__FORBIDDEN_POTION);
                invisibleAdd(entries, ModItems.SP5__GOD_POTION);
                invisibleAdd(entries, ModItems.SP5__END_CAKE);
                invisibleAdd(entries, ModItems.SP5__END_MILK);
                invisibleAdd(entries, ModItems.SP5__CORCODUS_FRUIT);
                invisibleAdd(entries, ModItems.SP5__END_VINES);
                invisibleAdd(entries, ModItems.MCD__DIAMOND_KEY);
                invisibleAdd(entries, ModItems.MCD__GOLD_KEY);
                invisibleAdd(entries, ModItems.SP5__END_BREAD);
                invisibleAdd(entries, ModItems.SP5__END_WHEAT);
                invisibleAdd(entries, ModItems.SP5__END_WHEAT_SEEDS);
                invisibleAdd(entries, ModItems.SP5__NAVI_FRUIT);
                invisibleAdd(entries, ModItems.SP5__END_BEEF);
                invisibleAdd(entries, ModItems.SP5__COOKED_END_BEEF);
                invisibleAdd(entries, ArchivedBlocks.ENDMERALD_ORE);
                invisibleAdd(entries, ArchivedBlocks.ENDMERALD_BLOCK);
                invisibleAdd(entries, ArchivedBlocks.ENDERITE_ORE);
                invisibleAdd(entries, ArchivedBlocks.ENDERITE_BLOCK);
                invisibleAdd(entries, ArchivedBlocks.ASTEROID_RESIDUES);
                invisibleAdd(entries, ArchivedBlocks.SOLID_ROCK);
                invisibleAdd(entries, ArchivedBlocks.END_GRASS);
                invisibleAdd(entries, ArchivedBlocks.BLUISHE_GRASS);
                invisibleAdd(entries, ArchivedBlocks.ANT_JAM_BLOCK);
                invisibleAdd(entries, ArchivedBlocks.SWEET_BERRY_JAM_BLOCK);
                invisibleAdd(entries, ArchivedBlocks.SUSPICIOUS_COARSE_DIRT);
                invisibleAdd(entries, ArchivedBlocks.TRANSPARENT_BLOCK);
                invisibleAdd(entries, ArchivedBlocks.END_WART_BLOCK);
                invisibleAdd(entries, ArchivedBlocks.BLUE_WART);
                invisibleAdd(entries, ArchivedBlocks.END_STEM);
                invisibleAdd(entries, ArchivedBlocks.END_HYPHAE);
                invisibleAdd(entries, ArchivedBlocks.STRIPPED_END_STEM);
                invisibleAdd(entries, ArchivedBlocks.STRIPPED_END_HYPHAE);
                invisibleAdd(entries, ArchivedBlocks.ENDLIGHT);
                invisibleAdd(entries, ArchivedBlocks.END_PLANKS);
                invisibleAdd(entries, ArchivedBlocks.END_STAIRS);
                invisibleAdd(entries, ArchivedBlocks.END_SLAB);
                invisibleAdd(entries, ArchivedBlocks.BLUISHE_STEM);
                invisibleAdd(entries, ArchivedBlocks.BLUISHE_HYPHAE);
                invisibleAdd(entries, ArchivedBlocks.BLUISHE_LIGHT_STEM);
                invisibleAdd(entries, ArchivedBlocks.BLUISHE_LIGHT_HYPHAE);
                invisibleAdd(entries, ArchivedBlocks.STRIPPED_BLUISHE_STEM);
                invisibleAdd(entries, ArchivedBlocks.STRIPPED_BLUISHE_HYPHAE);
                invisibleAdd(entries, ArchivedBlocks.BLUISHE_PLANKS);
                invisibleAdd(entries, ArchivedBlocks.BLUISHE_STAIRS);
                invisibleAdd(entries, ArchivedBlocks.BLUISHE_SLAB);
                invisibleAdd(entries, ArchivedBlocks.AZALEA_LOG);
                invisibleAdd(entries, ArchivedBlocks.AZALEA_WOOD);
                invisibleAdd(entries, ArchivedBlocks.STRIPPED_AZALEA_LOG);
                invisibleAdd(entries, ArchivedBlocks.STRIPPED_AZALEA_WOOD);
                invisibleAdd(entries, ArchivedBlocks.AZALEA_PLANKS);
                invisibleAdd(entries, ArchivedBlocks.AZALEA_STAIRS);
                invisibleAdd(entries, ArchivedBlocks.AZALEA_SLAB);
                invisibleAdd(entries, ArchivedBlocks.MOSSIER_COBBLESTONE);
                invisibleAdd(entries, ArchivedBlocks.MOSSIER_OAK_PLANKS);
                invisibleAdd(entries, ArchivedBlocks.MOSSIER_SPRUCE_PLANKS);
                invisibleAdd(entries, ArchivedBlocks.APPLE_CRATE);
                invisibleAdd(entries, ArchivedBlocks.BEETROOT_CRATE);
                invisibleAdd(entries, ArchivedBlocks.CARROT_CRATE);
                invisibleAdd(entries, ArchivedBlocks.POTATO_CRATE);
                invisibleAdd(entries, ArchivedBlocks.GOLDEN_APPLE_CRATE);
                invisibleAdd(entries, ArchivedBlocks.GOLDEN_CARROT_CRATE);
                invisibleAdd(entries, ArchivedBlocks.SWEET_BERRY_SACK);
                invisibleAdd(entries, ArchivedBlocks.GLOW_BERRY_SACK);
                invisibleAdd(entries, ArchivedBlocks.COCOA_BEANS_SACK);
                invisibleAdd(entries, ArchivedBlocks.GUNPOWDER_SACK);
                invisibleAdd(entries, ArchivedBlocks.NETHER_WART_SACK);
                invisibleAdd(entries, ArchivedBlocks.STICK_BLOCK);
                invisibleAdd(entries, ArchivedBlocks.SUGAR_CANE_BLOCK);
                invisibleAdd(entries, ArchivedBlocks.CACTUS_BLOCK);
                invisibleAdd(entries, ArchivedBlocks.CHORUS_FRUIT_BLOCK);
                invisibleAdd(entries, ArchivedBlocks.ANDESITE_PILLAR);
                invisibleAdd(entries, ArchivedBlocks.DIORITE_PILLAR);
                invisibleAdd(entries, ArchivedBlocks.GRANITE_PILLAR);
                invisibleAdd(entries, ArchivedBlocks.CAVE_ROOTS);
                invisibleAdd(entries, ArchivedItems.ANT_BOTTLE);
                invisibleAdd(entries, ArchivedItems.BOTTLE_OF_ANT_JAM);
                invisibleAdd(entries, ArchivedItems.MUSIC_DISC_WITHERSTORM);
                invisibleAdd(entries, ArchivedItems.DISC_FRAGMENT_WITHERSTORM);
                invisibleAdd(entries, ArchivedItems.ENDERITE_APPLE);
                invisibleAdd(entries, ArchivedItems.ENCHANTED_ENDERITE_APPLE);
                invisibleAdd(entries, ArchivedItems.ENDER_STICK);
                invisibleAdd(entries, ArchivedItems.ENDMERALD);
                invisibleAdd(entries, ArchivedItems.MELTE_RESIDUES);
                invisibleAdd(entries, ArchivedItems.ENDERITE_INGOT);
                invisibleAdd(entries, ArchivedItems.ENDERITE_HELMET);
                invisibleAdd(entries, ArchivedItems.ENDERITE_CHESTPLATE);
                invisibleAdd(entries, ArchivedItems.ENDERITE_LEGGINGS);
                invisibleAdd(entries, ArchivedItems.ENDERITE_BOOTS);
                invisibleAdd(entries, ArchivedItems.ENDERITE_SWORD);
                invisibleAdd(entries, ArchivedItems.ENDERITE_AXE);
                invisibleAdd(entries, ArchivedItems.ENDERITE_SHOVEL);
                invisibleAdd(entries, ArchivedItems.ENDERITE_HOE);
                invisibleAdd(entries, ArchivedItems.ENDERITE_PICKAXE);
                invisibleAdd(entries, ModItems.BP__OMINOUS_BOTTLE);
                invisibleAdd(entries, ModItems.H__ANOMALITE_SWORD1);
                invisibleAdd(entries, ModItems.H__ANOMALITE_SWORD2);
                invisibleAdd(entries, ModItems.H__ANOMALITE_PICKAXE1);
                invisibleAdd(entries, ModItems.H__ANOMALITE_PICKAXE2);
                invisibleAdd(entries, ModItems.H__PLASMA_1);
                invisibleAdd(entries, ModItems.H__PLASMA_2);
            }).build());
    public static ItemGroup ABYSS = SkyBlock.BuiltinRegistries.registerItemGroup("classified",
            FabricItemGroup.builder().displayName(Text.literal("The Abyss Chapter II (Y3Z0N)")).icon(() -> new ItemStack(GhostItems.Z__LOGO3)).entries((displayContext, entries) -> {
                entries.add(ModItems.ABYSS__ABERYTHE_GEM);
                entries.add(ModItems.ABYSS__ABERYTHE_HELMET);
                entries.add(ModItems.ABYSS__ABERYTHE_CHESTPLATE);
                entries.add(ModItems.ABYSS__ABERYTHE_LEGGINGS);
                entries.add(ModItems.ABYSS__ABERYTHE_BOOTS);
                entries.add(ModItems.ABYSS__ABERYTHE_SWORD);
                entries.add(ModItems.ABYSS__ABERYTHE_AXE);
                entries.add(ModItems.ABYSS__ABERYTHE_SHOVEL);
                entries.add(ModItems.ABYSS__ABERYTHE_HOE);
                entries.add(ModItems.ABYSS__ABERYTHE_PICKAXE);
                entries.add(ModItems.ABYSS__LORAN);
                entries.add(ModItems.ABYSS__ABYSS_PORTAL_ACTIVATOR);
                entries.add(ModBlocks.ABYSS__UNSTABLE_OBSIDIAN);
                entries.add(ModBlocks.ABYSS__ABYSS_DIRT);
                entries.add(ModBlocks.ABYSS__ROMA_MUD);
                entries.add(ModBlocks.ABYSS__ROMA_MUD_CURSED);
                entries.add(ModBlocks.ABYSS__ABYSS_GRAVEL);
                entries.add(ModBlocks.ABYSS__INFECTED_PEAT);
                entries.add(ModBlocks.ABYSS__STONE_RACKLE);
                entries.add(ModBlocks.ABYSS__BLARU_MOSS);
                entries.add(ModBlocks.ABYSS__GLOWING_BLARU_MOSS);
                entries.add(ModBlocks.ABYSS__BLARU_GRASS);
                entries.add(ModBlocks.ABYSS__ABYSS_SPORES);
                entries.add(ModBlocks.ABYSS__TESLA_FLOWER);
                entries.add(ModBlocks.ABYSS__VIGILANT_VERSA);
                entries.add(ModBlocks.ABYSS__EXOLIUS_MAXIMUS);
                entries.add(ModBlocks.ABYSS__YOUNG_EXOLIUS_MAXIMUS);
                entries.add(ModBlocks.ABYSS__VIGILANT_GRASS);
                entries.add(ModBlocks.ABYSS__BLUE_VIGILANT_GRASS);
                entries.add(ModBlocks.ABYSS__VIGILANT_MOSS);
                entries.add(ModBlocks.ABYSS__INFUSED_MAGMA);
                entries.add(ModBlocks.ABYSS__ABYSS_STONE);
                entries.add(ModBlocks.ABYSS__ABYSS_DIAMOND_ORE);
                entries.add(ModBlocks.ABYSS__ABYSS_EMERALD_ORE);
                entries.add(ModBlocks.ABYSS__ABYSS_GOLD_ORE);
                entries.add(ModBlocks.ABYSS__ABYSS_IRON_ORE);
                entries.add(ModBlocks.ABYSS__ABYSS_IGNISITHE_ORE);
                entries.add(ModBlocks.ABYSS__ABYSS_ABERYTHE_ORE);
                entries.add(ModBlocks.ABYSS__ABYSS_ABORANYS_ORE);
                entries.add(ModBlocks.ABYSS__ABYSS_FUSION_ORE);
                entries.add(ModBlocks.ABYSS__ABYSS_GARNITE_ORE);
                entries.add(ModBlocks.ABYSS__ABYSS_GLACERYTHE_ORE);
                entries.add(ModBlocks.ABYSS__ABYSS_INCORYTHE_ORE);
                entries.add(ModBlocks.ABYSS__ABYSS_LORAN_ORE);
                entries.add(ModBlocks.ABYSS__PURPLE_SHROOMLIGHT);
                entries.add(ModBlocks.ABYSS__DARK_BLUE_SHROOMLIGHT);
                entries.add(ModBlocks.ABYSS__BLUE_SHROOMLIGHT);
                entries.add(ModBlocks.ABYSS__ABYSS_JUNGLE_LOG);
                entries.add(ModBlocks.ABYSS__ABYSS_JUNGLE_WOOD);
                entries.add(ModBlocks.ABYSS__STRIPPED_ABYSS_JUNGLE_LOG);
                entries.add(ModBlocks.ABYSS__STRIPPED_ABYSS_JUNGLE_WOOD);
                entries.add(ModBlocks.ABYSS__ABYSS_JUNGLE_PLANKS);
                entries.add(ModBlocks.ABYSS__ABYSS_JUNGLE_STAIRS);
                entries.add(ModBlocks.ABYSS__ABYSS_JUNGLE_SLAB);
                entries.add(ModBlocks.ABYSS__ABYSS_JUNGLE_LEAVES);
                entries.add(ModBlocks.ABYSS__BLARU_LOG);
                entries.add(ModBlocks.ABYSS__BLARU_WOOD);
                entries.add(ModBlocks.ABYSS__STRIPPED_BLARU_LOG);
                entries.add(ModBlocks.ABYSS__STRIPPED_BLARU_WOOD);
                entries.add(ModBlocks.ABYSS__BLARU_PLANKS);
                entries.add(ModBlocks.ABYSS__BLARU_STAIRS);
                entries.add(ModBlocks.ABYSS__BLARU_SLAB);
                entries.add(ModBlocks.ABYSS__BLARU_LEAVES);
                entries.add(ModBlocks.ABYSS__FROZEN_LOG);
                entries.add(ModBlocks.ABYSS__FROZEN_WOOD);
                entries.add(ModBlocks.ABYSS__STRIPPED_FROZEN_LOG);
                entries.add(ModBlocks.ABYSS__STRIPPED_FROZEN_WOOD);
                entries.add(ModBlocks.ABYSS__FROZEN_PLANKS);
                entries.add(ModBlocks.ABYSS__VERTICAL_FROZEN_PLANKS);
                entries.add(ModBlocks.ABYSS__CARVED_FROZEN_PLANKS);
                entries.add(ModBlocks.ABYSS__FROZEN_STAIRS);
                entries.add(ModBlocks.ABYSS__FROZEN_SLAB);
                entries.add(ModBlocks.ABYSS__FROZEN_LEAVES);
                entries.add(ModBlocks.ABYSS__SLIMED_LOG);
                entries.add(ModBlocks.ABYSS__SLIMED_WOOD);
                entries.add(ModBlocks.ABYSS__STRIPPED_SLIMED_LOG);
                entries.add(ModBlocks.ABYSS__STRIPPED_SLIMED_WOOD);
                entries.add(ModBlocks.ABYSS__SLIMED_PLANKS);
                entries.add(ModBlocks.ABYSS__SLIMED_STAIRS);
                entries.add(ModBlocks.ABYSS__SLIMED_SLAB);
                entries.add(ModBlocks.ABYSS__ABYSS_SLIME_BLOCK);
                entries.add(ModBlocks.ABYSS__VIGILANT_LOG);
                entries.add(ModBlocks.ABYSS__VIGILANT_WOOD);
                entries.add(ModBlocks.ABYSS__STRIPPED_VIGILANT_LOG);
                entries.add(ModBlocks.ABYSS__STRIPPED_VIGILANT_WOOD);
                entries.add(ModBlocks.ABYSS__VIGILANT_PLANKS);
                entries.add(ModBlocks.ABYSS__VIGILANT_STAIRS);
                entries.add(ModBlocks.ABYSS__VIGILANT_SLAB);
                entries.add(ModBlocks.ABYSS__VIGILANT_LEAVES);
                entries.add(ModBlocks.ABYSS__BOG_SHROOM_LOG);
                entries.add(ModBlocks.ABYSS__BOG_SHROOM_WOOD);
                entries.add(ModBlocks.ABYSS__STRIPPED_BOG_SHROOM_LOG);
                entries.add(ModBlocks.ABYSS__STRIPPED_BOG_SHROOM_WOOD);
                entries.add(ModBlocks.ABYSS__BOG_SHROOM_PLANKS);
                entries.add(ModBlocks.ABYSS__BOG_SHROOM_STAIRS);
                entries.add(ModBlocks.ABYSS__BOG_SHROOM_SLAB);
                entries.add(ModBlocks.ABYSS__BOG_SHROOM_LEAVES);
                entries.add(ModBlocks.ABYSS__SAL_SHROOM_LOG);
                entries.add(ModBlocks.ABYSS__SAL_SHROOM_WOOD);
                entries.add(ModBlocks.ABYSS__STRIPPED_SAL_SHROOM_LOG);
                entries.add(ModBlocks.ABYSS__STRIPPED_SAL_SHROOM_WOOD);
                entries.add(ModBlocks.ABYSS__SAL_SHROOM_PLANKS);
                entries.add(ModBlocks.ABYSS__SAL_SHROOM_STAIRS);
                entries.add(ModBlocks.ABYSS__SAL_SHROOM_SLAB);
                entries.add(ModBlocks.ABYSS__SAL_SHROOM_LEAVES);
                entries.add(ModBlocks.ABYSS__ABYSCULK_LOG);
                entries.add(ModBlocks.ABYSS__ABYSCULK_WOOD);
                entries.add(ModBlocks.ABYSS__ABYSCULK_PLANKS);
                entries.add(ModBlocks.ABYSS__ABYSCULK_STAIRS);
                entries.add(ModBlocks.ABYSS__ABYSCULK_SLAB);
            }).build());
    public static ItemGroup QUARK = SkyBlock.BuiltinRegistries.registerItemGroup("quark",
            FabricItemGroup.builder().displayName(Text.literal("Quark (Vazkii)")).icon(() -> new ItemStack(GhostItems.Z__LOGO4)).entries((displayContext, entries) -> {
                entries.add(ModBlocks.QUARK__APPLE_CRATE);
                entries.add(ModBlocks.QUARK__BEETROOT_CRATE);
                entries.add(ModBlocks.QUARK__CARROT_CRATE);
                entries.add(ModBlocks.QUARK__POTATO_CRATE);
                entries.add(ModBlocks.QUARK__GOLDEN_APPLE_CRATE);
                entries.add(ModBlocks.QUARK__GOLDEN_CARROT_CRATE);
                entries.add(ModBlocks.QUARK__SWEET_BERRY_SACK);
                entries.add(ModBlocks.QUARK__GLOW_BERRY_SACK);
                entries.add(ModBlocks.QUARK__COCOA_BEAN_SACK);
                entries.add(ModBlocks.QUARK__GUNPOWDER_SACK);
                entries.add(ModBlocks.QUARK__NETHER_WART_SACK);
                entries.add(ModBlocks.QUARK__STICK_BLOCK);
                entries.add(ModBlocks.QUARK__SUGAR_CANE_BLOCK);
                entries.add(ModBlocks.QUARK__CACTUS_BLOCK);
                entries.add(ModBlocks.QUARK__CHORUS_FRUIT_BLOCK);

                entries.add(ModBlocks.QUARK__ANDESITE_BRICKS);
                entries.add(ModBlocks.QUARK__CHISELED_ANDESITE_BRICKS);
                entries.add(ModBlocks.QUARK__ANDESITE_PILLAR);
                entries.add(Blocks.POLISHED_ANDESITE);
                entries.add(Blocks.POLISHED_ANDESITE_STAIRS);
                entries.add(Blocks.POLISHED_ANDESITE_SLAB);
                entries.add(ModBlocks.QUARK__ANDESITE_BRICK_STAIRS);
                entries.add(ModBlocks.QUARK__ANDESITE_BRICK_SLAB);
                entries.add(Blocks.ANDESITE_STAIRS);
                entries.add(Blocks.ANDESITE_SLAB);
                entries.add(ModBlocks.QUARK__DIORITE_BRICKS);
                entries.add(ModBlocks.QUARK__CHISELED_DIORITE_BRICKS);
                entries.add(ModBlocks.QUARK__DIORITE_PILLAR);
                entries.add(Blocks.POLISHED_DIORITE);
                entries.add(Blocks.POLISHED_DIORITE_STAIRS);
                entries.add(Blocks.POLISHED_DIORITE_SLAB);
                entries.add(ModBlocks.QUARK__DIORITE_BRICK_STAIRS);
                entries.add(ModBlocks.QUARK__DIORITE_BRICK_SLAB);
                entries.add(Blocks.DIORITE_STAIRS);
                entries.add(Blocks.DIORITE_SLAB);
                entries.add(ModBlocks.QUARK__GRANITE_BRICKS);
                entries.add(ModBlocks.QUARK__CHISELED_GRANITE_BRICKS);
                entries.add(ModBlocks.QUARK__GRANITE_PILLAR);
                entries.add(Blocks.POLISHED_GRANITE);
                entries.add(Blocks.POLISHED_GRANITE_STAIRS);
                entries.add(Blocks.POLISHED_GRANITE_SLAB);
                entries.add(ModBlocks.QUARK__GRANITE_BRICK_STAIRS);
                entries.add(ModBlocks.QUARK__GRANITE_BRICK_SLAB);
                entries.add(Blocks.GRANITE_STAIRS);
                entries.add(Blocks.GRANITE_SLAB);
                entries.add(ModBlocks.QUARK__DRIPSTONE_BRICKS);
                entries.add(ModBlocks.QUARK__CHISELED_DRIPSTONE_BRICKS);
                entries.add(ModBlocks.QUARK__DRIPSTONE_PILLAR);
                entries.add(ModBlocks.QUARK__POLISHED_DRIPSTONE);
                entries.add(ModBlocks.QUARK__POLISHED_DRIPSTONE_STAIRS);
                entries.add(ModBlocks.QUARK__POLISHED_DRIPSTONE_SLAB);
                entries.add(ModBlocks.QUARK__DRIPSTONE_BRICK_STAIRS);
                entries.add(ModBlocks.QUARK__DRIPSTONE_BRICK_SLAB);
                entries.add(ModBlocks.QUARK__DRIPSTONE_STAIRS);
                entries.add(ModBlocks.QUARK__DRIPSTONE_SLAB);
                entries.add(ModBlocks.QUARK__CALCITE_BRICKS);
                entries.add(ModBlocks.QUARK__CHISELED_CALCITE_BRICKS);
                entries.add(ModBlocks.QUARK__CALCITE_PILLAR);
                entries.add(ModBlocks.QUARK__POLISHED_CALCITE);
                entries.add(ModBlocks.QUARK__POLISHED_CALCITE_STAIRS);
                entries.add(ModBlocks.QUARK__POLISHED_CALCITE_SLAB);
                entries.add(ModBlocks.QUARK__CALCITE_BRICK_STAIRS);
                entries.add(ModBlocks.QUARK__CALCITE_BRICK_SLAB);
                entries.add(ModBlocks.QUARK__CALCITE_STAIRS);
                entries.add(ModBlocks.QUARK__CALCITE_SLAB);

                entries.add(ModBlocks.QUARK__CAVE_ROOTS);
                entries.add(ModBlocks.QUARK__VERTICAL_OAK_PLANKS);
                entries.add(ModBlocks.QUARK__VERTICAL_SPRUCE_PLANKS);
                entries.add(ModBlocks.QUARK__VERTICAL_BIRCH_PLANKS);
                entries.add(ModBlocks.QUARK__VERTICAL_JUNGLE_PLANKS);
                entries.add(ModBlocks.QUARK__VERTICAL_ACACIA_PLANKS);
                entries.add(ModBlocks.QUARK__VERTICAL_DARK_OAK_PLANKS);
                entries.add(ModBlocks.QUARK__VERTICAL_MANGROVE_PLANKS);
                entries.add(ModBlocks.QUARK__VERTICAL_CHERRY_PLANKS);
                entries.add(ModBlocks.QUARK__VERTICAL_BAMBOO_PLANKS);
                entries.add(ModBlocks.QUARK__VERTICAL_CRIMSON_PLANKS);
                entries.add(ModBlocks.QUARK__VERTICAL_WARPED_PLANKS);
                entries.add(ModBlocks.ABYSS__VERTICAL_FROZEN_PLANKS);
            }).build());

    public static void register() {
        SkyBlock.LOGGER.info("[SkyBlock MultiMod] Registering Item Groups for " + SkyBlock.MOD_ID);
    }
    public static void invisibleAdd(ItemGroup.Entries entries, ItemConvertible itemConvertible) {
        entries.add(itemConvertible, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
    }

    private static void addSpaces(ItemGroup.Entries entries, int used_spaces, int spaces) {
        for (byte b : NullItem.VALUES) {
            if (spaces != 0) {
                ItemStack itemStack = new ItemStack(GhostItems.Z__NULL);
                itemStack.set(ModDataComponentTypes.SIMPLE_BYTE_VALUE_COMPONENT, new SimpleByteValueComponent(used_spaces + b));
                spaces = spaces-1;
            entries.add(itemStack, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
            }
        }
    }
    private static void addTiles(ItemGroup.Entries entries, int used_tiles, int tiles) {
        for (byte b : NullItem.VALUES) {
            if (tiles != 0) {
                ItemStack itemStack = new ItemStack(GhostItems.Z__TILE_BLANK);
                itemStack.set(ModDataComponentTypes.SIMPLE_BYTE_VALUE_COMPONENT, new SimpleByteValueComponent(used_tiles + b));
                tiles = tiles-1;
                entries.add(itemStack, ItemGroup.StackVisibility.PARENT_TAB_ONLY);
            }
        }
    }
}
